// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUsers(ctx context.Context, arg AddUsersParams) error
	ChangeUserEmail(ctx context.Context, arg ChangeUserEmailParams) (User, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	DeleteNotes(ctx context.Context, id pgtype.UUID) (Note, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (User, error)
	EditNotes(ctx context.Context, arg EditNotesParams) (Note, error)
	GetNotesByID(ctx context.Context, id pgtype.UUID) (Note, error)
	GetUserAuth(ctx context.Context, email string) (GetUserAuthRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListAllNotes(ctx context.Context, arg ListAllNotesParams) ([]Note, error)
	ListUserNotes(ctx context.Context, arg ListUserNotesParams) ([]Note, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
}

var _ Querier = (*Queries)(nil)
