// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUsers = `-- name: AddUsers :exec
INSERT INTO users (email, first_name, last_name, password_hash)
VALUES ($1, $2, $3, $4)
`

type AddUsersParams struct {
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) AddUsers(ctx context.Context, arg AddUsersParams) error {
	_, err := q.db.Exec(ctx, addUsers,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.PasswordHash,
	)
	return err
}

const changeUserEmail = `-- name: ChangeUserEmail :one
UPDATE users
SET email = $1
WHERE id = $2
RETURNING id, email, first_name, last_name, password_hash, created_at, is_active
`

type ChangeUserEmailParams struct {
	Email string      `json:"email"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) ChangeUserEmail(ctx context.Context, arg ChangeUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, changeUserEmail, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (user_id, title, body)
VALUES ($1, $2, $3)
`

type CreateNoteParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.Exec(ctx, createNote, arg.UserID, arg.Title, arg.Body)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const editNotes = `-- name: EditNotes :one
UPDATE notes
SET title = $1, 
    body = $2, 
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, title, body, created_at, updated_at
`

type EditNotesParams struct {
	Title string      `json:"title"`
	Body  string      `json:"body"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) EditNotes(ctx context.Context, arg EditNotesParams) (Note, error) {
	row := q.db.QueryRow(ctx, editNotes, arg.Title, arg.Body, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesByID = `-- name: GetNotesByID :one
SELECT id, user_id, title, body, created_at, updated_at FROM notes
WHERE id = $1
`

func (q *Queries) GetNotesByID(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNotesByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuth = `-- name: GetUserAuth :exec
SELECT id,email, password_hash FROM users
WHERE email = $1
`

func (q *Queries) GetUserAuth(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, getUserAuth, email)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT email, first_name, last_name, created_at FROM users 
WHERE id = $1
`

type GetUserByIDRow struct {
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
	)
	return i, err
}

const listAllNotes = `-- name: ListAllNotes :many
SELECT id, user_id, title, body, created_at, updated_at FROM notes
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListAllNotesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllNotes(ctx context.Context, arg ListAllNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listAllNotes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotes = `-- name: ListUserNotes :many
SELECT id, user_id, title, body, created_at, updated_at FROM notes 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListUserNotesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserNotes(ctx context.Context, arg ListUserNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listUserNotes, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, first_name, last_name, password_hash, created_at, is_active FROM users
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
